name: Create Release

# Workflow activated when I push a new tag starting with 'v'
on:
  push:
    tags:
      - 'v*'

# Add permissions for the job to be able to create a release
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}

          body: |
            Automated release of Hakai version ${{ github.ref_name }}.
            Download the JAR file below to play.

          files: app/build/libs/*-all.jar

          prerelease: ${{ contains(github.ref, '-BETA') || contains(github.ref, '-alpha') || contains(github.ref, '-rc') }}